name: "Build python wheels for major platforms"

on:
  workflow_dispatch: {}


jobs:
  make-wheels:
    name: Make ${{ matrix.os }} wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]
      fail-fast: false

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3

      - name: "Build wheels"
        uses: pypa/cibuildwheel@v2.8.1
        with:
          package-dir: .
        env:
          CIBW_ENVIRONMENT: >
            SKSTAN_REPACKAGE_CMDSTAN=TRUE
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_BUILD: cp37-* cp38-* cp39-* cp310-*
          CIBW_SKIP: "*musllinux*"
          CIBW_ARCHS: native
          CIBW_BUILD_FRONTEND: build
          CIBW_TEST_REQUIRES: pytest scikit-learn
          CIBW_TEST_COMMAND: pytest --runslow -v --pyargs sk_stan_regression

      - name: "Upload wheel as artifact"
        uses: actions/upload-artifact@v3
        with:
          name: artifact-${{ matrix.os }}-wheel
          path: "./**/*.whl"

  make-sdist:
    name: Make source distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: pipx run build --sdist

    - uses: actions/upload-artifact@v3
      with:
        name: artifact-source-dist
        path: "./**/dist/*.tar.gz"
