name: scikit-stan tests

on:
  push:
    branches:
      - 'develop'
      - 'main'
    tags:
      - '**'
  pull_request:
  workflow_dispatch: {}


env:
  CMDSTAN_VERSION: "2.31.0"

jobs:
  scikit-stan:
    name: tests
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out github
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies (python)
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements-test.txt

      - name: Run flake8
        run: |
          flake8 scikit_stan test

      - name: Run mypy
        if: matrix.python-version == '3.7' # only run on oldest version for now
        run: |
          mypy scikit_stan

      - name: CmdStan installation cacheing
        uses: actions/cache@v3
        with:
          path: ~/.cmdstan
          key: ${{ runner.os }}-cmdstan-${{ env.CMDSTAN_VERSION }}

      - name: Install CmdStan (Linux, macOS)
        if: matrix.os != 'windows-latest'
        run: |
          python -m cmdstanpy.install_cmdstan --version "${{ env.CMDSTAN_VERSION }}" --cores 2

      - name: Install CmdStan (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          python -m cmdstanpy.install_cmdstan --compiler --version "${{ env.CMDSTAN_VERSION }}" --cores 2

      - name: Install package
        run: |
          pip install .

      - name: Run tests
        run: |
          pytest --runslow -v --cov --cov-report term
